[package]
name = "iced_winit"
version = "0.1.0-alpha"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A winit runtime for Iced"
license = "MIT"
repository = "https://github.com/hecrj/iced"
documentation = "https://docs.rs/iced_winit"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[features]
debug = []

[dependencies]
winit = "0.22"
window_clipboard = "0.1"
log = "0.4"

[dependencies.iced_native]
version = "0.1.0"
path = "../native"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.6"
